// ══════════════════════════════════════════════════════════════════════════════
// FHIR Export — HL7 FHIR R4 Observation export for MAP/MMAS-8 assessments
// BP-INT-03: Enables EHR integration (Epic, Cerner, etc.) via FHIR webhooks
// ══════════════════════════════════════════════════════════════════════════════

'use strict';

// LOINC codes for MAP instrument (to be assigned by LOINC committee)
// Using local codes until formal LOINC assignment
const FHIR_CODING = {
  MAP_SCORE:      { system: 'https://adherence.cc/fhir/codes', code: 'MAP-COMPOSITE', display: 'MAP Medication Adherence Composite Score' },
  MAP_PHENOTYPE:  { system: 'https://adherence.cc/fhir/codes', code: 'MAP-PHENOTYPE', display: 'MAP Behavioral Adherence Phenotype' },
  MMAS8_SCORE:    { system: 'http://loinc.org', code: '89972-9', display: 'Morisky Medication Adherence Scale 8-item' },
  PEACS_BASE:     { system: 'https://adherence.cc/fhir/codes', code: 'PEACS-BASE', display: 'PEACS Architecture Domain Score (30-day)' },
  PEACS_MVMT:     { system: 'https://adherence.cc/fhir/codes', code: 'PEACS-MVMT', display: 'PEACS Execution Domain Score (7-day)' },
  PEACS_STRATA:   { system: 'https://adherence.cc/fhir/codes', code: 'PEACS-STRATA', display: 'PEACS Context Domain Score (90-day)' },
};

/**
 * Converts a single ATLAS assessment record to a FHIR R4 Observation resource.
 * @param {Object} record - ATLAS assessment record
 * @param {string} patientRef - FHIR Patient reference (e.g. "Patient/12345")
 * @returns {Object} FHIR Observation resource
 */
function assessmentToFHIRObservation(record, patientRef) {
  const phenotype = (typeof deriveMAPPhenotype === 'function') ? deriveMAPPhenotype(record) : (record.map_phenotype || 'PA');
  const score = record.score !== undefined ? record.score : null;
  const ts = record.timestamp ? new Date(record.timestamp).toISOString() : new Date().toISOString();

  const obs = {
    resourceType: 'Observation',
    id: record.id || record.patient_number + '-' + record.timestamp,
    status: 'final',
    category: [{
      coding: [{ system: 'http://terminology.hl7.org/CodeSystem/observation-category', code: 'survey', display: 'Survey' }]
    }],
    code: { coding: [FHIR_CODING.MAP_SCORE], text: 'MAP Medication Adherence Assessment' },
    subject: { reference: patientRef || ('Patient/' + (record.patient_number || 'unknown')) },
    effectiveDateTime: ts,
    issued: ts,
    performer: [{ display: record.workspace || 'ATLAS Platform' }],
    note: [{ text: 'Generated by ATLAS Adherence Cartography Platform (adherence.cc)' }]
  };

  if (score !== null) {
    obs.valueQuantity = { value: score, unit: 'score', system: 'http://unitsofmeasure.org', code: '{score}' };
  }

  obs.component = [
    {
      code: { coding: [FHIR_CODING.MAP_PHENOTYPE] },
      valueCodeableConcept: {
        coding: [{ system: 'https://adherence.cc/fhir/codes/phenotype', code: phenotype }],
        text: { INA: 'Intentional Non-Adherent', UNA: 'Unintentional Non-Adherent', PA: 'Partially Adherent', A: 'Adherent' }[phenotype] || phenotype
      }
    }
  ];

  if (record.peacs_base !== undefined)   obs.component.push({ code: { coding: [FHIR_CODING.PEACS_BASE] },   valueQuantity: { value: record.peacs_base,   unit: 'score' } });
  if (record.peacs_mvmt !== undefined)   obs.component.push({ code: { coding: [FHIR_CODING.PEACS_MVMT] },   valueQuantity: { value: record.peacs_mvmt,   unit: 'score' } });
  if (record.peacs_strata !== undefined) obs.component.push({ code: { coding: [FHIR_CODING.PEACS_STRATA] }, valueQuantity: { value: record.peacs_strata, unit: 'score' } });

  return obs;
}

/**
 * Exports a cohort of ATLAS assessments as a FHIR R4 Bundle.
 * @param {Object[]} records - array of ATLAS assessment records
 * @returns {Object} FHIR Bundle resource
 */
function exportFHIRBundle(records) {
  const bundle = {
    resourceType: 'Bundle',
    id: 'atlas-export-' + Date.now(),
    type: 'collection',
    timestamp: new Date().toISOString(),
    meta: { source: 'https://adherence.cc', profile: ['https://adherence.cc/fhir/StructureDefinition/atlas-bundle'] },
    entry: records.map(r => ({
      fullUrl: 'urn:uuid:' + (r.id || crypto.randomUUID()),
      resource: assessmentToFHIRObservation(r)
    }))
  };
  return bundle;
}

/**
 * Downloads a FHIR Bundle as a JSON file.
 * @param {Object[]} records - array of ATLAS assessment records
 */
function downloadFHIRBundle(records) {
  if (typeof isSuperAdmin !== 'function' && typeof isPIMode !== 'function') return;
  const hasAccess = (typeof isSuperAdmin === 'function' && isSuperAdmin()) ||
                    (typeof isPIMode === 'function' && isPIMode()) ||
                    (typeof isInstitutionMode === 'function' && isInstitutionMode());
  if (!hasAccess) {
    if (typeof showToast === 'function') showToast('PI or higher access required for FHIR export.', 3000);
    return;
  }
  const bundle = exportFHIRBundle(records);
  const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/fhir+json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `atlas-fhir-bundle-${currentWorkspace}-${new Date().toISOString().slice(0,10)}.json`;
  a.click();
  URL.revokeObjectURL(url);
  if (typeof atlasAuditLog === 'function') atlasAuditLog('FHIR_EXPORT', { count: records.length });
}

// ── Webhook Configuration ─────────────────────────────────────────────────────

/**
 * Opens the FHIR webhook configuration panel.
 * @param {HTMLElement} container
 */
function openFHIRWebhookConfig(container) {
  if (!container) return;
  container.innerHTML = `
    <div style="font-family:'IBM Plex Mono',monospace;font-size:0.58rem;letter-spacing:0.18em;text-transform:uppercase;color:rgba(78,156,245,0.6);margin-bottom:6px;">Integrations · FHIR Webhook</div>
    <div style="font-family:'Cormorant Garamond',Georgia,serif;font-size:1.35rem;font-weight:300;color:var(--bright,#e8f0f8);margin-bottom:16px;">HL7 FHIR R4 Webhook</div>
    <p style="font-size:0.84rem;color:var(--muted,#6b8099);line-height:1.75;margin-bottom:20px;max-width:520px;">Configure a FHIR endpoint to receive MAP/MMAS-8 assessment results as FHIR Observations automatically after each patient assessment. Compatible with Epic FHIR, Cerner, and any FHIR R4 compliant server.</p>
    <div id="fhir-wh-form" style="max-width:520px;display:flex;flex-direction:column;gap:14px;">
      <div>
        <label style="font-family:'IBM Plex Mono',monospace;font-size:0.58rem;letter-spacing:0.12em;text-transform:uppercase;color:var(--muted,#6b8099);display:block;margin-bottom:5px;">FHIR Server Base URL</label>
        <input id="fhir-wh-url" type="url" placeholder="https://fhir.hospital.org/api/FHIR/R4"
          style="width:100%;box-sizing:border-box;background:rgba(255,255,255,0.04);border:1px solid rgba(78,156,245,0.2);border-radius:6px;padding:9px 12px;font-family:'IBM Plex Mono',monospace;font-size:0.80rem;color:var(--bright,#e8f0f8);outline:none;"/>
      </div>
      <div>
        <label style="font-family:'IBM Plex Mono',monospace;font-size:0.58rem;letter-spacing:0.12em;text-transform:uppercase;color:var(--muted,#6b8099);display:block;margin-bottom:5px;">Authentication Type</label>
        <select id="fhir-wh-auth" style="width:100%;background:rgba(255,255,255,0.04);border:1px solid rgba(78,156,245,0.2);border-radius:6px;padding:9px 12px;color:var(--bright,#e8f0f8);outline:none;">
          <option value="bearer">Bearer Token</option>
          <option value="basic">Basic Auth</option>
          <option value="none">None (internal/sandbox)</option>
        </select>
      </div>
      <div>
        <label style="font-family:'IBM Plex Mono',monospace;font-size:0.58rem;letter-spacing:0.12em;text-transform:uppercase;color:var(--muted,#6b8099);display:block;margin-bottom:5px;">Authorization Token / Credentials</label>
        <input id="fhir-wh-token" type="password" placeholder="Bearer token or user:password"
          style="width:100%;box-sizing:border-box;background:rgba(255,255,255,0.04);border:1px solid rgba(78,156,245,0.2);border-radius:6px;padding:9px 12px;font-family:'IBM Plex Mono',monospace;font-size:0.80rem;color:var(--bright,#e8f0f8);outline:none;"/>
      </div>
      <div id="fhir-wh-err" style="font-size:0.78rem;color:rgba(239,68,68,0.9);display:none;"></div>
      <div style="display:flex;gap:10px;">
        <button onclick="saveFHIRWebhook()" style="font-family:'IBM Plex Mono',monospace;font-size:0.66rem;letter-spacing:0.1em;text-transform:uppercase;background:rgba(78,156,245,0.1);border:1px solid rgba(78,156,245,0.3);color:rgba(78,156,245,0.9);padding:10px 18px;border-radius:7px;cursor:pointer;">Save Webhook →</button>
        <button onclick="testFHIRWebhook()" style="font-family:'IBM Plex Mono',monospace;font-size:0.66rem;letter-spacing:0.1em;text-transform:uppercase;background:none;border:1px solid rgba(255,255,255,0.15);color:var(--muted,#6b8099);padding:10px 18px;border-radius:7px;cursor:pointer;">Send Test Ping</button>
      </div>
    </div>`;
}

async function saveFHIRWebhook() {
  const url   = document.getElementById('fhir-wh-url')?.value.trim();
  const auth  = document.getElementById('fhir-wh-auth')?.value;
  const token = document.getElementById('fhir-wh-token')?.value.trim();
  const errEl = document.getElementById('fhir-wh-err');

  if (!url) { if (errEl) { errEl.textContent = 'FHIR server URL is required.'; errEl.style.display = 'block'; } return; }

  try {
    const res = await fetch(LAMBDA_URL + '/fhir-webhook-save', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + await _accGetToken() },
      body: JSON.stringify({ workspace: currentWorkspace, fhir_url: url, auth_type: auth, token })
    });
    if (!res.ok) throw new Error('Failed to save webhook configuration');
    if (typeof showToast === 'function') showToast('FHIR webhook saved. New assessments will be posted automatically.', 4000);
    if (typeof atlasAuditLog === 'function') atlasAuditLog('FHIR_WEBHOOK_SAVED', { fhir_url: url, auth_type: auth });
  } catch(e) {
    if (errEl) { errEl.textContent = 'Save failed: ' + e.message; errEl.style.display = 'block'; }
  }
}

async function testFHIRWebhook() {
  const testObs = assessmentToFHIRObservation({ score: 7.5, q1:0,q2:0,q3:0,q4:0,q5:1,q6:0,q7:0,q8:0, timestamp: Date.now(), patient_number: 'TEST-001' });
  const status = document.getElementById('fhir-wh-err');
  if (status) { status.textContent = 'Sending test ping…'; status.style.color = 'rgba(78,156,245,0.8)'; status.style.display = 'block'; }

  try {
    const res = await fetch(LAMBDA_URL + '/fhir-webhook-test', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + await _accGetToken() },
      body: JSON.stringify({ workspace: currentWorkspace, observation: testObs })
    });
    const data = await res.json();
    if (status) { status.textContent = '✓ Test ping successful: ' + (data.message || 'FHIR server responded 200'); status.style.color = 'rgba(46,201,138,0.9)'; }
  } catch(e) {
    if (status) { status.textContent = 'Test failed: ' + e.message; status.style.color = 'rgba(239,68,68,0.9)'; }
  }
}
